name: CI

on: [push]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install -y ros-geometry-msgs
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
